### ISSUE TITLE
Application 1.11.0 does not start

### ISSUE THREAD

**Issue by pannox** [meetrevision/revision-tool#87] opened 2024-08-01 11:36 UTC
The application does not start, a black window appears that closes after a few seconds

1. Open "C:\Program Files (x86)\Revision Tool\revitool.exe"
2. See error

**Screenshots**
![Immagine 2024-08-01 133415](https://github.com/user-attachments/assets/93cbc18c-2c62-41a9-aebe-79d74367bbf1)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.3880
 - Playbook Version: ReviOS 11 24.06
 - Revision Tool Version: 1.11

**Comment by melo936** [comment] 2024-08-02 06:12
Try reinstalling

**Comment by pannox** [comment] 2024-08-02 06:33
> Try reinstalling

Already done, but the problem persists. I've made several attempts.

**Comment by DudeBeast01** [comment] 2024-08-03 05:58
Same for me, I'm using 24H2 version 26100.1150 and the command prompt appears and then disappears. I've tried lots of stuff but it still happens. It also sometimes does nothing.

**Comment by melo936** [comment] 2024-08-03 10:12
Please uninstall the current Revision Tool and install this one instead. Once installed run Revision Tool and send logs from `%temp%\Revision-Tool\Logs`

https://github.com/meetrevision/revision-tool/releases/download/1.11.1/RevisionTool-Setup.exe

**Comment by DudeBeast01** [comment] 2024-08-04 00:09
There is no Revision-Tool folder in the temp folder on my computer

**Comment by JusticeWay** [comment] 2024-08-04 15:54
No work app, 1.11 and 1.11.1, folder Revision-Tool\Logs - not on the computer

Windows 11 Pro 23H2 22631.3880
Windows Feature Experience Pack 1000.22700.1020.0

Playbook Version: ReviOS 11 24.06

**Comment by JusticeWay** [comment] 2024-08-04 16:00
Nothing works after version 1.10.8

**Comment by denoid24** [comment] 2024-08-04 19:06
several latest versions of the app doesn't work at all on windows  11 Pro 23H2 22631.3880. Closing right after launch. The last fully functional version -  dates back to june.

**Comment by DudeBeast01** [comment] 2024-08-04 21:05
Serval ones don’t work for me too

**Comment by melo936** [comment] 2024-08-06 15:41
Does Revision Tool open after disabling your graphics drivers via Device Manager?

**Comment by JusticeWay** [comment] 2024-08-07 18:09
> Does Revision Tool open after disabling your graphics drivers via Device Manager?

Yes, work 

But there is no desire to use the computer without drivers

**Comment by DudeBeast01** [comment] 2024-08-07 21:12
After disabling all of them my laptop is now showing black on the screen.

**Comment by melo936** [comment] 2024-08-08 07:54
Unfortunately, nothing we can do more. We will need to wait [this to get fixed](https://github.com/flutter/flutter/issues/150546)

**Comment by Noatitauaggi** [comment] 2024-08-08 07:59
> Unfortunately, nothing we can do more. We will need to wait [this to get fixed](https://github.com/flutter/flutter/issues/150546) 

But why is version 1.10.8 working fine? 

It stopped working after the latest updates

**Comment by melo936** [comment] 2024-08-08 08:02
> It stopped working after the latest updates

Revision Tool 1.10.8 used older Flutter engine and it didn't have the bug

**Comment by Noatitauaggi** [comment] 2024-08-08 08:04
> > It stopped working after the latest updates
> 
> 
> 
> Revision Tool 1.10.8 used older Flutter engine and it didn't have the bug

Maybe we should use a stable version of Flutter for the app?

**Comment by melo936** [comment] 2024-08-08 08:15
We have always been using a stable version of Flutter; the bug is due to recent changes in the Flutter engine in the stable branch. 

Reverting to the older engine would most likely require breaking changes, therefore not worth to do it, because it is going to be fixed soon.

**Comment by Noatitauaggi** [comment] 2024-08-08 08:31
> We have always been using a stable version of Flutter; the bug is due to recent changes in the Flutter engine in the stable branch. 
> 
> 
> 
> Reverting to the older engine would most likely require breaking changes, therefore not worth to do it, because it is going to be fixed soon. 

Will you immediately update the app as soon as Flutter is fixed?

**Comment by DudeBeast01** [comment] 2024-08-08 08:58
I’ll update as early as possible

**Comment by JusticeWay** [comment] 2024-08-08 10:29
There is a fix version and it helps most people
https://github.com/flutter/flutter/issues/150546#issuecomment-2265931842

**Comment by JusticeWay** [comment] 2024-08-08 10:33
There is a fix and it helps most people, but you need the involvement of the app developer.
https://github.com/flutter/flutter/issues/150546#issuecomment-2265931842

Demo app good work...

**Comment by melo936** [comment] 2024-08-08 16:21
> Will you immediately update the app as soon as Flutter is fixed?

Yes



> There is a fix and it helps most people, but you need the involvement of the app developer. [flutter/flutter#150546 (comment)](https://github.com/flutter/flutter/issues/150546#issuecomment-2265931842)
> 
> Demo app good work...

The PR isn't merged and not landed in the stable branch.

**Comment by melo936** [comment] 2024-08-22 14:34
Please try out [Revision Tool 1.12.1](https://github.com/meetrevision/revision-tool/releases/tag/1.12.1) and verify if it works now.

**Comment by pannox** [comment] 2024-08-28 17:29
same thing doesn't work for me

**Comment by Bejukoro** [comment] 2024-09-05 17:23
I have the same problem on my device. I think this might be caused by an app called LocalSend, and when I closed this app, the Revision Tool launched and worked fine. LocalSend is also built using Flutter, so could this be the cause of the issue?

**Comment by melo936** [comment] 2024-09-28 05:41
https://github.com/meetrevision/revision-tool/issues/86#issuecomment-2380415965

Please try this out and report back if it's fixed

**Closed** 2024-12-08 11:28 UTC
Labels: bug
